name: "Theme Validation"
description: "Validate the themes"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
        cache-dependency-path: package-lock.json

    - name: print actor
      shell: bash
      run: echo ${{ github.actor }}

    - name: install deps
      run: npm ci
      shell: bash

    - name: REUSE compliance check
      uses: fsfe/reuse-action@v2
      
    - name: create generated dir
      run: mkdir ./assets/generated
      shell: bash
      
    - name: create dependencies
      run: npm run generate:licenses; npm run generate:images; npm run generate:charging-stations; npm run generate:service-worker
      shell: bash
      
    - name: sync translations
      run: npm run generate:translations
      shell: bash

    - name: generate layeroverview
      run: npm run reset:layeroverview
      shell: bash
      
    - name: run tests
      run: npm run test
      shell: bash

    - name: Prepare deploy
      run: npm run prepare-deploy
      shell: bash
